### ISSUE TITLE
I don't get a notification when testing push notifications

### ISSUE THREAD

**Issue by AdrienneMendrik** [eyra/eylixir#169]
I activated push notifications and allowed them in my browser (google chrome)

I then click the send notification button, but I do not get a notification:

![Screenshot 2021-09-14 at 20 32 04](https://user-images.githubusercontent.com/79082794/133438049-6d38f6cc-52fe-4f76-90d2-4611c4b25a36.png)

Notifications are enabled in the browser settings:

![Screenshot 2021-09-14 at 20 41 54](https://user-images.githubusercontent.com/79082794/133437940-407585c2-519a-4402-99fc-d7dd62cd04b0.png)

**Comment by vloothuis** [comment]
This has been fixed by updating a dependency.
