### ISSUE TITLE
Publish after retracting gives announcement that not all fields are filled

### ISSUE THREAD

**Issue by AdrienneMendrik** [eyra/eylixir#191]
I did the following when creating a campaign:
1) fill in all required fields
2) publish campaign
3) retract campaign
4) click publish again

I expected that it would be published again.
Instead it gives a message that not all required fields are filled, but I cannot find any missing values.

![Screenshot 2021-10-15 at 22 01 12](https://user-images.githubusercontent.com/79082794/137546872-6896a08c-4ab6-4e22-a4af-e4ece73d09fa.png)

**Comment by emielvdveen** [comment]
Fixed in Panl 0.3.2. Can be tested from now on link.dev.eyra.co
